function m(c,a,b,d){c.i.ha(c.Y,a,b,d)}function r(c,a,b,d){c.i.m?m(c,a,b,d):c.i.Gb()._OnMessageFromDOM({type:"event",component:c.Y,handler:a,dispatchOpts:d||null,data:b,responseId:null})}function t(c,a,b){c.i.h(c.Y,a,b)}function u(c,a){for(const [b,d]of a)t(c,b,d)}window.R=class{constructor(c,a){this.i=c;this.Y=a}Oa(){}};window.rc=class{constructor(){this.N=-1}};"use strict";function aa(c,a){t(c,"get-element",b=>{const d=v(c,b.elementId);return a(d,b)})}
function v(c,a){c=c.J.get(a);if(!c)throw Error(`no element with id ${a}`);return c.ka}
window.Qa=class extends self.R{constructor(c,a){super(c,a);this.J=new Map;this.W=!0;u(this,[["create",()=>{throw Error("required override");}],["destroy",b=>{b=b.elementId;const d=v(this,b);this.W&&d.parentElement.removeChild(d);this.J.delete(b)}],["set-visible",b=>{if(this.W){var d=this.J.get(b.elementId),e=d.ka;d.kb?e.style.display=b.isVisible?"":"none":d.Zb=!!b.isVisible}}],["update-position",b=>{if(this.W){var d=this.J.get(b.elementId),e=d.ka,f=this.i;e.style.left=b.left+"px";e.style.top=b.top+
"px";e.style.width=b.width+"px";e.style.height=b.height+"px";var h=b.fontSize;null!==h&&(e.style.fontSize=h+"em");h=b.htmlIndex;d.cc=h;h=f.Ra(h);h!==d.C&&(e.remove(),f.ga(h).appendChild(e),d.C=h,f.xa());b=b.htmlZIndex;b!==d.Aa&&(d.Aa=b,f.xa());d.kb||(d.kb=!0,d.Zb&&(e.style.display=""))}}],["update-state",b=>{v(this,b.elementId);throw Error("required override");}],["focus",b=>{const d=v(this,b.elementId);b.focus?d.focus():d.blur()}],["set-css-style",b=>{const d=v(this,b.elementId),e=b.prop;b=b.val;
e.startsWith("--")?d.style.setProperty(e,b):d.style[e]=b}],["set-attribute",b=>{v(this,b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{v(this,b.elementId).removeAttribute(b.name)}]]);aa(this,b=>b)}};"use strict";const w=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),x=/android/i.test(navigator.userAgent),ba=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);let y=0;
function z(c){const a=document.createElement("script");a.async=!1;a.type="module";return c.hc?new Promise(b=>{const d="c3_resolve_"+y;++y;self[d]=b;a.textContent=c.lc+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((b,d)=>{a.onload=b;a.onerror=d;a.src=c;document.head.appendChild(a)})}
async function ca(){if(!navigator.userActivation||"undefined"===typeof OffscreenCanvas)return!1;try{let c=!1;const a=new Worker(URL.createObjectURL(new Blob(['\n\tself.addEventListener("message", () =>\n\t{\n\t\ttry {\n\t\t\tconst offscreenCanvas = new OffscreenCanvas(32, 32);\n\t\t\tconst gl = offscreenCanvas.getContext("webgl");\n\t\t\tself.postMessage(!!gl);\n\t\t}\n\t\tcatch (err)\n\t\t{\n\t\t\tconsole.warn("Feature detection worker error:", err);\n\t\t\tself.postMessage(false);\n\t\t}\n\t});'],{type:"text/javascript"})),
{get type(){c=!0}}),b=await new Promise(d=>{a.addEventListener("message",e=>{a.terminate();d(e.data)});a.postMessage("")});return c&&b}catch(c){return console.warn("Error feature detecting worker mode: ",c),!1}}let A=new Audio;
const da={"audio/webm; codecs=opus":!!A.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!A.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!A.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!A.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!A.canPlayType("audio/mp4"),"audio/mpeg":!!A.canPlayType("audio/mpeg")};A=null;async function ea(c){c=await B(c);return(new TextDecoder("utf-8")).decode(c)}
function B(c){return new Promise((a,b)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>b(e);d.readAsArrayBuffer(c)})}const C=[];let D=0;window.RealFile=window.File;const E=[],F=new Map,G=new Map;let fa=0;const ha=[];self.runOnStartup=function(c){if("function"!==typeof c)throw Error("runOnStartup called without a function");ha.push(c)};const ia=new Set(["cordova","playable-ad","instant-games"]);let ja=!1;
window.U=class c{constructor(a){this.m=a.nc;this.aa=null;this.l="";this.L=a.kc;this.da={};this.Fa=this.O=null;this.I=[];this.F=null;this.mb=!0;this.j=[];this.Ja=[];this.Ka=!1;this.ob=()=>this.Eb();this.lb=!1;this.Z=null;this.K=-1;this.bc=()=>this.Pb();this.ba=new Set;this.Ma=null;this.pb=[];this.g=a.qb;this.Ca="file"===location.protocol.substr(0,4);if("playable-ad"===this.g||"instant-games"===this.g)this.m=!1;ba&&(this.m=!1);if("cordova"===this.g&&this.m&&x){const b=/Chrome\/(\d+)/i.exec(navigator.userAgent);
b&&90<=parseInt(b[1],10)||(this.m=!1)}this.G()?self.chrome.webview.addEventListener("message",b=>this.bb(b.data)):"macos-wkwebview"===this.g&&(self.C3WrapperOnMessage=b=>this.bb(b));this.la=this.v=null;"html5"!==this.g||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.h("canvas","update-size",b=>this.Tb(b));this.h("canvas","set-html-layer-count",
b=>this._OnSetHTMLLayerCount(b));this.h("canvas","cleanup-html-layers",()=>this.Kb());this.h("runtime","cordova-fetch-local-file",b=>this.Lb(b));this.h("runtime","create-job-worker",()=>this.Mb());this.h("runtime","send-wrapper-extension-message",b=>this.Sb(b));"cordova"===this.g?document.addEventListener("deviceready",()=>this.$a(a)):this.$a(a)}Sa(){return this.j[0].canvas}Ra(a){return Math.min(a,this.j.length-1)}ga(a){if(0>a||a>=this.j.length)throw new RangeError("invalid canvas layer");return this.j[a].ea}_GetHTMLWrapElement(a){return this.ga(a)}vb(){return w&&
"cordova"===this.g}T(){const a=navigator.userAgent;return w&&ia.has(this.g)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}tb(){return x}Ta(){return x&&ia.has(this.g)}Ua(){return"windows-webview2"===this.g||!!("preview"===this.g&&window.chrome&&window.chrome.webview&&window.chrome.webview.postMessage)}G(){return this.Ua()||"xbox-uwp-webview2"===this.g}async $a(a){this.m&&!await ca()&&(this.m=!1);"macos-wkwebview"===this.g?this.V({type:"ready"}):this.G()&&(this.Wb(),this.pb=(await this.Jb()).registeredComponentIds);
if("playable-ad"===this.g){this.v=self.c3_base64files;this.la={};await this.Bb();for(let d=0,e=a.P.length;d<e;++d){var b=a.P[d];this.la.hasOwnProperty(b)?a.P[d]={hc:!0,lc:this.la[b]}:this.v.hasOwnProperty(b)&&(a.P[d]=URL.createObjectURL(this.v[b]))}a.pa=[]}if("nwjs"===this.g&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.Va(()=>{d++;document.documentElement.style.opacity=0===d%2?"1":"0.999"})}a.jc?this.l=a.jc:(b=location.origin,this.l=("null"===b?"file:///":b)+location.pathname,b=this.l.lastIndexOf("/"),
-1!==b&&(this.l=this.l.substr(0,b+1)));a.pc&&(this.da=a.pc);b=new MessageChannel;this.aa=b.port1;this.aa.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.Ob(d));this.Z=new self.wb(this);await ka(this.Z);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",
d)}this.m?await this.Ib(a,b.port2):await this.Hb(a,b.port2)}ua(a){a=this.da.hasOwnProperty(a)?this.da[a]:a.endsWith("/workermain.js")&&this.da.hasOwnProperty("workermain.js")?this.da["workermain.js"]:"playable-ad"===this.g&&this.v.hasOwnProperty(a)?this.v[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async ra(a,b,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.g&&this.Ca)return a=await this.qa(d.fc?a:this.L+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),
d);a=new URL(a,b);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}u(){return Math.max(window.innerWidth,1)}o(){return Math.max(window.innerHeight,1)}sa(){return this.G()||(new Set(["cordova","nwjs","macos-wkwebview"])).has(this.g)?"standalone":window.matchMedia("(display-mode: fullscreen)").matches?"fullscreen":window.matchMedia("(display-mode: standalone)").matches?
"standalone":window.matchMedia("(display-mode: minimal-ui)").matches?"minimal-ui":navigator.standalone?"standalone":"browser"}Za(a){var b=this.l,d=location.href,e=this.u(),f=this.o(),h=this.sa(),g=window.devicePixelRatio,k=c.S(),l=a.uc,n=window.cr_previewImageBlobs||this.v,p=window.cr_previewProjectFileBlobs,q=window.cr_previewProjectFiles,xa=window.cr_swClientId||"";a=a.qb;var ya=(new URLSearchParams(self.location.search)).has("debug"),K=this.Z;return{runtimeBaseUrl:b,previewUrl:d,windowInnerWidth:e,
windowInnerHeight:f,cssDisplayMode:h,devicePixelRatio:g,isFullscreen:k,projectData:l,previewImageBlobs:n,previewProjectFileBlobs:p,previewProjectFileSWUrls:q,swClientId:xa,exportType:a,isDebug:ya,ife:!!self.tc,jobScheduler:{inputPort:K.Ba,outputPort:K.Ia,maxNumWorkers:K.$b},supportedAudioFormats:da,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.L+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.L+"opus.wasm.wasm",isFileProtocol:this.Ca,isiOSCordova:this.vb(),isiOSWebView:this.T(),
isWindowsWebView2:this.Ua(),isAnyWebView2Wrapper:this.G(),wrapperComponentIds:this.pb,isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Ib(a,b){const d=this.ua(a.oc);"preview"===this.g?(this.O=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((l,n)=>{const p=q=>{this.O.removeEventListener("message",p);q.data&&"ok"===q.data.type?l():n()};this.O.addEventListener("message",p);this.O.postMessage({type:"construct-worker-init","import":(new URL(d,this.l)).toString()})})):
this.O=await this.ra(d,this.l,{type:"module",name:"Runtime",fc:!0});const e=document.createElement("canvas");e.style.display="none";const f=e.transferControlToOffscreen();document.body.appendChild(e);const h=document.createElement("div");h.className="c3htmlwrap";document.body.appendChild(h);this.j.push({canvas:e,ea:h});window.c3canvas=e;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let g=a.pa||[],k=a.P;g=await Promise.all(g.map(l=>this.H(l)));k=await Promise.all(k.map(l=>this.H(l)));
if("cordova"===this.g)for(let l=0,n=a.oa.length;l<n;++l){const p=a.oa[l],q=p[0];if(q===a.Na||"scriptsInEvents.js"===q||q.endsWith("/scriptsInEvents.js"))p[1]=await this.H(q)}this.O.postMessage(Object.assign(this.Za(a),{type:"init-runtime",isInWorker:!0,messagePort:b,canvas:f,workerDependencyScripts:g,engineScripts:k,projectScripts:a.oa,mainProjectScript:a.Na,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[b,f,...la(this.Z)]);this.I=E.map(l=>new l(this));this.Ya();H(e);I(h);ma(this.F);self.c3_callFunction=
(l,n)=>{var p=this.F;return p.i.xb(p.Y,{name:l,params:n})};"preview"===this.g&&(self.goToLastErrorScript=()=>this.ha("runtime","go-to-last-error-script"))}async Hb(a,b){const d=document.createElement("canvas");d.style.display="none";document.body.appendChild(d);var e=document.createElement("div");e.className="c3htmlwrap";document.body.appendChild(e);this.j.push({canvas:d,ea:e});window.c3canvas=d;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.I=E.map(g=>new g(this));this.Ya();
H(d);I(e);e=a.P.map(g=>"string"===typeof g?(new URL(g,this.l)).toString():g);if(Array.isArray(a.pa)){var f=[...a.pa].map(g=>g instanceof Blob?URL.createObjectURL(g):g);e.unshift(...f)}e=await Promise.all(e.map(g=>this.H(g)));await Promise.all(e.map(g=>z(g)));e=self.C3_ProjectScriptsStatus;f=a.Na;const h=a.oa;for(let [g,k]of h)if(k||(k=g),g===f)try{k=await this.H(k),await z(k),"preview"!==this.g||e[g]||this.cb(g,"main script did not run to completion")}catch(l){this.cb(g,l)}else if("scriptsInEvents.js"===
g||g.endsWith("/scriptsInEvents.js"))k=await this.H(k),await z(k);"preview"===this.g&&"object"!==typeof self.qc.sc?(this.ja(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.Za(a),{isInWorker:!1,messagePort:b,canvas:d,runOnStartupFunctions:ha}),ma(this.F),this.ab(),this.Fa=self.C3_CreateRuntime(a),
await self.C3_InitRuntime(this.Fa,a))}cb(a,b){this.ja();console.error(`[Preview] Failed to load project main script (${a}): `,b);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}ab(){this.ja()}ja(){const a=window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async Mb(){const a=await na(this.Z);return{outputPort:a,transferables:[a]}}Tb(a){if(!this.lb){var b=
a.styleWidth+"px",d=a.styleHeight+"px",e=a.marginLeft+"px",f=a.marginTop+"px";for(const {canvas:h,ea:g}of this.j)h.style.width=b,h.style.height=d,h.style.marginLeft=e,h.style.marginTop=f,g.style.width=b,g.style.height=d,g.style.marginLeft=e,g.style.marginTop=f,this.mb&&(h.style.display="",g.style.display="");document.documentElement.style.setProperty("--construct-scale",a.displayScale);this.mb=!1}}_OnSetHTMLLayerCount(a){var b=a.count,d=a.immediate,e=a.styleWidth+"px",f=a.styleHeight+"px";const h=
a.marginLeft+"px",g=a.marginTop+"px";a=[];const k=[];if(b<this.j.length)for(;this.j.length>b;){const {canvas:l,ea:n}=this.j.pop();n.remove();this.m&&!d?this.Ja.push(l):l.remove()}else if(b>this.j.length)for(let l=0,n=b-this.j.length;l<n;++l)b=document.createElement("canvas"),b.classList.add("c3overlay"),this.m?(d=b.transferControlToOffscreen(),a.push(d),k.push(d)):a.push(b),document.body.appendChild(b),d=document.createElement("div"),d.classList.add("c3htmlwrap","c3overlay"),document.body.appendChild(d),
b.style.width=e,b.style.height=f,b.style.marginLeft=h,b.style.marginTop=g,d.style.width=e,d.style.height=f,d.style.marginLeft=h,d.style.marginTop=g,H(b),I(d),this.j.push({canvas:b,ea:d});for(const l of this.I)if(l instanceof window.Qa&&l.W)for(const n of l.J.values())e=l.i.Ra(n.cc),f=n.C,-1!==e&&-1!==f&&e!==f&&(f=n.ka,f.remove(),l.i.ga(e).appendChild(f),n.C=e);this.xa();return{addedCanvases:a,transferables:k}}Kb(){for(const a of this.Ja)a.remove();this.Ja.length=0}xa(){this.Ka||(this.Ka=!0,this.Va(this.ob))}Eb(){this.Vb(this.ob);
this.Ka=!1;let a=[];for(var b of this.I)if(b instanceof window.Qa){var d=b.W?[...b.J.values()]:null;d&&a.push(...d)}a.sort((h,g)=>{const k=h.C,l=g.C;return k!==l?k-l:h.Aa-g.Aa});let e=d=b=0,f=a.length;for(;e<f;++e){const h=a[e];h.C!==b&&(this.Xa(b,a.slice(d,e)),b=h.C,d=e)}d<e&&this.Xa(b,a.slice(d,e))}Xa(a,b){if(!(1>=b.length||a>=this.j.length)){b=b.map(k=>k.ka);var d=new Set(b);a=this.ga(a);for(var e=Array.from(a.children).filter(k=>d.has(k)),f=0,h=Math.min(b.length,e.length);f<h&&b[f]===e[f];++f);
for(var g=f;g<h;++g)e[g].remove();for(g=f;g<h;++g)a.appendChild(b[g])}}Gb(){if(this.m)throw Error("not available in worker mode");return this.Fa}ha(a,b,d,e){this.aa.postMessage({type:"event",component:a,handler:b,dispatchOpts:e||null,data:d,responseId:null},void 0)}xb(a,b){const d=fa++,e=new Promise((f,h)=>{G.set(d,{resolve:f,reject:h})});this.aa.postMessage({type:"event",component:a,handler:"js-invoke-function",dispatchOpts:null,data:b,responseId:d},void 0);return e}_OnMessageFromRuntime(a){const b=
a.type;if("event"===b)return this.Nb(a);if("result"===b)this.Qb(a);else if("runtime-ready"===b)this.Rb();else if("alert-error"===b)this.ja(),alert(a.message);else if("creating-runtime"===b)this.ab();else throw Error(`unknown message '${b}'`);}Nb(a){const b=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=F.get(b))if(a=a.get(d)){var h=null;try{h=a(e)}catch(g){console.error(`Exception in '${b}' handler '${d}':`,g);null!==f&&this.ia(f,!1,""+g);return}if(null===f)return h;h&&h.then?h.then(g=>this.ia(f,
!0,g)).catch(g=>{console.error(`Rejection from '${b}' handler '${d}':`,g);this.ia(f,!1,""+g)}):this.ia(f,!0,h)}else console.warn(`[DOM] No handler '${d}' for component '${b}'`);else console.warn(`[DOM] No event handlers for component '${b}'`)}ia(a,b,d){let e;d&&d.transferables&&(e=d.transferables);this.aa.postMessage({type:"result",responseId:a,isOk:b,result:d},e)}Qb(a){const b=a.responseId,d=a.isOk;a=a.result;const e=G.get(b);d?e.resolve(a):e.reject(a);G.delete(b)}h(a,b,d){let e=F.get(a);e||(e=new Map,
F.set(a,e));if(e.has(b))throw Error(`[DOM] Component '${a}' already has handler '${b}'`);e.set(b,d)}static fa(a){if(E.includes(a))throw Error("DOM handler already added");E.push(a)}Ya(){for(const a of this.I)if("runtime"===a.Y){this.F=a;return}throw Error("cannot find runtime DOM handler");}Ob(a){this.ha("debugger","message",a)}Rb(){for(const a of this.I)a.Oa()}static S(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||ja)}static eb(a){ja=!!a}Va(a){this.ba.add(a);
this.wa()}Vb(a){this.ba.delete(a);0===this.ba.size&&this.Wa()}wa(){-1===this.K&&0<this.ba.size&&(this.K=requestAnimationFrame(this.bc))}Wa(){-1!==this.K&&(cancelAnimationFrame(this.K),this.K=-1)}Pb(){this.K=-1;for(const a of this.ba)a();this.wa()}va(){this.F.va()}yb(){this.lb=!0}sb(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}ub(a){return!this.sb(a)}async H(a){return"cordova"===this.g&&(a.startsWith("file:")||this.Ca&&this.ub(a))?(a.startsWith(this.l)&&
(a=a.substr(this.l.length)),a=await this.qa(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Lb(a){const b=a.filename;switch(a.as){case "text":return await this.rb(b);case "buffer":return await this.qa(b);default:throw Error("unsupported type");}}Pa(a){const b=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(b,f=>{f.file(d,e)},e)})}async rb(a){a=await this.Pa(a);return await ea(a)}ta(){if(C.length&&!(8<=D)){D++;
var a=C.shift();this.Cb(a.filename,a.mc,a.ec)}}qa(a){return new Promise((b,d)=>{C.push({filename:a,mc:e=>{D--;this.ta();b(e)},ec:e=>{D--;this.ta();d(e)}});this.ta()})}async Cb(a,b,d){try{const e=await this.Pa(a),f=await B(e);b(f)}catch(e){d(e)}}bb(a){if("entered-fullscreen"===a)c.eb(!0),J(this.F);else if("exited-fullscreen"===a)c.eb(!1),J(this.F);else if("object"===typeof a){const b=a.type;"directory-handles"!==b&&("wrapper-init-response"===b?(this.Ma(a),this.Ma=null):"extension-message"===b?this.ha("runtime",
"wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a))}else console.warn("Unknown wrapper message: ",a)}Sb(a){this.V({type:"extension-message",componentId:a.componentId,messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}V(a){this.G()?window.chrome.webview.postMessage(JSON.stringify(a)):"macos-wkwebview"===this.g&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}Wb(){window.moveTo=(a,b)=>{this.V({type:"set-window-position",windowX:Math.ceil(a),
windowY:Math.ceil(b)})};window.resizeTo=(a,b)=>{this.V({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(b)})}}Jb(){return this.G()?new Promise(a=>{this.Ma=a;this.V({type:"wrapper-init"})}):Promise.resolve()}async Bb(){const a=[];for(const [b,d]of Object.entries(this.v))a.push(this.Ab(b,d));await Promise.all(a)}async Ab(a,b){if("object"===typeof b)this.v[a]=new Blob([b.str],{type:b.type}),this.la[a]=b.str;else{let d=await this.Fb(b);d||(d=this.Db(b));this.v[a]=d}}async Fb(a){try{return await (await fetch(a)).blob()}catch(b){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
b),null}}Db(a){a=this.Ub(a);return this.zb(a.data,a.ic)}Ub(a){var b=a.indexOf(",");if(0>b)throw new URIError("expected comma in data: uri");var d=a.substring(b+1);b=a.substring(5,b).split(";");a=b[0]||"";const e=b[2];d="base64"===b[1]||"base64"===e?atob(d):decodeURIComponent(d);return{ic:a,data:d}}zb(a,b){var d=a.length;let e=d>>2,f=new Uint8Array(d),h=new Uint32Array(f.buffer,0,e),g,k;for(k=g=0;g<e;++g)h[g]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=
3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],{type:b})}};"use strict";const L=self.U,oa=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),M={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},N={dispatchUserScriptEvent:!0},O={dispatchRuntimeEvent:!0};function pa(c){return new Promise((a,b)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>b(e);d.rel="stylesheet";d.href=c;document.head.appendChild(d)})}
function qa(c){return new Promise((a,b)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>b(e);d.src=c})}async function ra(c){c=URL.createObjectURL(c);try{return await qa(c)}finally{URL.revokeObjectURL(c)}}function sa(c){do{if(c.parentNode&&c.hasAttribute("contenteditable"))return!0;c=c.parentNode}while(c);return!1}const ta=new Set(["input","textarea","datalist","select"]),ua=new Set(["canvas","body","html"]);
function P(c){c.target.tagName&&ua.has(c.target.tagName.toLowerCase())&&c.preventDefault()}function Q(c){c.target.tagName&&c.target.classList.contains("c3htmlwrap")&&c.preventDefault()}function va(c){(c.metaKey||c.ctrlKey)&&c.preventDefault()}
self.C3_GetSvgImageSize=async function(c){c=await ra(c);if(0<c.width&&0<c.height)return[c.width,c.height];c.style.position="absolute";c.style.left="0px";c.style.top="0px";c.style.visibility="hidden";document.body.appendChild(c);const a=c.getBoundingClientRect();document.body.removeChild(c);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(c,a,b,d,e){c=await ra(c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(c,0,0,a,b);return f};
let S=!1;document.addEventListener("pause",()=>S=!0);document.addEventListener("resume",()=>S=!1);function H(c){c.addEventListener("selectstart",P);c.addEventListener("gesturehold",P);c.addEventListener("pointerdown",P)}function I(c){c.addEventListener("selectstart",Q);c.addEventListener("gesturehold",Q);c.addEventListener("touchstart",Q)}function ma(c){c.ib=!0;c.Ea=c.i.u();c.$=c.i.o()}
function J(c){if(!c.s){var a=L.S();a&&"any"!==c.La&&wa(c);m(c,"fullscreenchange",{isFullscreen:a,innerWidth:c.u(),innerHeight:c.o()})}}async function za(c){await Promise.all(c.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Aa(c){var a=c.imageBitmapOpts;c=await self.C3_RasterSvgImageBlob(c.blob,c.imageWidth,c.imageHeight,c.surfaceWidth,c.surfaceHeight);a=a?await createImageBitmap(c,a):await createImageBitmap(c);return{imageBitmap:a,transferables:[a]}}async function Ba(c){return await self.C3_GetSvgImageSize(c.blob)}function Ca(c){window.c3_postToMessagePort&&(c.from="runtime",window.c3_postToMessagePort(c))}
function Da(c){self.setTimeout(()=>{c.hb=!0},1E3);"cordova"===c.i.g?(document.addEventListener("pause",()=>T(c,!0)),document.addEventListener("resume",()=>T(c,!1))):document.addEventListener("visibilitychange",()=>T(c,"hidden"===document.visibilityState));c.ma=!("hidden"!==document.visibilityState&&!S);return{isSuspended:c.ma}}
function Ea(c){c.gb||(c.gb=!0,window.addEventListener("deviceorientation",a=>{c.s||m(c,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},M)}),window.addEventListener("deviceorientationabsolute",a=>{c.s||m(c,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},M)}))}
function Fa(c){c.fb||(c.fb=!0,window.addEventListener("devicemotion",a=>{if(!c.s){var b=null,d=a.acceleration;d&&(b={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});m(c,"devicemotion",{acceleration:b,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},M)}}))}async function Ga(c){await pa(c.url)}
function Ha(c,a){c.jb=a.message;-1===c.za&&(c.za=setTimeout(()=>{c.za=-1;const b=document.getElementById("exportToVideoMessage");b&&(b.textContent=c.jb)},250))}function V(c,a){console.warn("[Construct] Fullscreen request failed: ",a);m(c,"fullscreenerror",{isFullscreen:L.S(),innerWidth:c.u(),innerHeight:c.o()})}
function T(c,a){c.ma!==a&&((c.ma=a)?c.i.Wa():c.i.wa(),m(c,"visibilitychange",{hidden:a}),!a&&c.i.T()&&(c=()=>{document.scrollingElement.scrollTop=0;document.scrollingElement.scrollLeft=0},setTimeout(c,50),setTimeout(c,100),setTimeout(c,250),setTimeout(c,500)))}
function Ia(c,a,b){"Backspace"===b.key&&P(b);"nwjs"===c.i.g&&"u"===b.key&&(b.ctrlKey||b.metaKey)&&b.preventDefault();if(!c.s){var d=oa.get(b.code)||b.code;r(c,a,{code:d,key:b.key,which:b.which,repeat:b.repeat,altKey:b.altKey,ctrlKey:b.ctrlKey,metaKey:b.metaKey,shiftKey:b.shiftKey,timeStamp:b.timeStamp},M)}}
function W(c,a,b,d){c.s||b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents||r(c,a,{button:b.button,buttons:b.buttons,clientX:b.clientX,clientY:b.clientY+c.B,pageX:b.pageX,pageY:b.pageY+c.B,movementX:b.movementX||0,movementY:b.movementY||0,timeStamp:b.timeStamp},d)}
function X(c,a,b){if(!c.s){var d=0;"mouse"===b.pointerType&&(d=c.Ha);r(c,a,{pointerId:b.pointerId,pointerType:b.pointerType,button:b.button,buttons:b.buttons,lastButtons:d,clientX:b.clientX,clientY:b.clientY+c.B,pageX:b.pageX,pageY:b.pageY+c.B,movementX:b.movementX||0,movementY:b.movementY||0,width:b.width||0,height:b.height||0,pressure:b.pressure||0,tangentialPressure:b.tangentialPressure||0,tiltX:b.tiltX||0,tiltY:b.tiltY||0,twist:b.twist||0,timeStamp:b.timeStamp},M);"mouse"===b.pointerType&&(c.Ha=
b.buttons)}}function Y(c,a,b){document.body.style.position="";document.body.style.overflow="";document.body.style.transform="";c.B=0;if(0<b){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-b)/2,a>b&&(a=b),0>a&&(a=0),0<a&&(document.body.style.position="absolute",document.body.style.overflow="visible",document.body.style.transform=`translateY(${-a}px)`,c.B=a))}}
function Ja(c,a,b,d){const e=c.u(),f=c.o();c.M=-1;e!=a||f!=b?m(c,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:L.S(),cssDisplayMode:c.i.sa()}):10>d&&Ka(c,e,f,d+1)}function Ka(c,a,b,d){-1!==c.M&&clearTimeout(c.M);c.M=setTimeout(()=>Ja(c,a,b,d),48)}
function wa(c){c=c.La;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(c).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(c):screen.webkitLockOrientation?a=screen.webkitLockOrientation(c):screen.mozLockOrientation?a=screen.mozLockOrientation(c):screen.msLockOrientation&&(a=screen.msLockOrientation(c));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function La(c){return!c||c===document||c===window||c===document.body||"canvas"===c.tagName.toLowerCase()}
L.fa(class extends self.R{constructor(c){super(c,"runtime");this.ib=!1;this.M=-1;this.La="any";this.ma=this.fb=this.gb=!1;this.na=document.createElement("div");this.na.className="c3-screen-reader-text";this.na.setAttribute("aria-live","polite");document.body.appendChild(this.na);this.D=null;this.s=!1;this.jb="";this.za=-1;this.hb=!1;this.Ea=c.u();this.$=c.o();this.B=this.ca=0;c.h("runtime","invoke-download",b=>{const d=b.url;b=b.filename;const e=document.createElement("a"),f=document.body;e.textContent=
b;e.href=d;e.download=b;f.appendChild(e);e.click();f.removeChild(e)});c.h("runtime","load-webfonts",b=>za(b));c.h("runtime","raster-svg-image",b=>Aa(b));c.h("runtime","get-svg-image-size",b=>Ba(b));c.h("runtime","set-target-orientation",b=>{this.La=b.targetOrientation});c.h("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});c.h("runtime","post-to-debugger",b=>Ca(b));c.h("runtime","go-to-script",b=>Ca(b));c.h("runtime","before-start-ticking",()=>Da(this));c.h("runtime","debug-highlight",
b=>{if(b.show){this.D||(this.D=document.createElement("div"),this.D.id="inspectOutline",document.body.appendChild(this.D));var d=this.D;d.style.display="";d.style.left=b.left-1+"px";d.style.top=b.top-1+"px";d.style.width=b.width+2+"px";d.style.height=b.height+2+"px";d.textContent=b.name}else this.D&&(this.D.style.display="none")});c.h("runtime","enable-device-orientation",()=>Ea(this));c.h("runtime","enable-device-motion",()=>Fa(this));c.h("runtime","add-stylesheet",b=>Ga(b));c.h("runtime","script-create-worker",
b=>{const d=b.port2;(new Worker(b.url,b.opts)).postMessage({type:"construct-worker-init",port2:d},[d])});c.h("runtime","alert",b=>{alert(b.message)});c.h("runtime","screen-reader-text",b=>{var d=b.type;"create"===d?(d=document.createElement("p"),d.id="c3-sr-"+b.id,d.textContent=b.text,this.na.appendChild(d)):"update"===d?(d=document.getElementById("c3-sr-"+b.id))?d.textContent=b.text:console.warn(`[Construct] Missing screen reader text with id ${b.id}`):"release"===d?(d=document.getElementById("c3-sr-"+
b.id))?d.remove():console.warn(`[Construct] Missing screen reader text with id ${b.id}`):console.warn(`[Construct] Unknown screen reader text update '${d}'`)});c.h("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});c.h("runtime","set-exporting-to-video",b=>{this.s=!0;const d=document.createElement("h1");d.id="exportToVideoMessage";d.textContent=b.message;document.body.prepend(d);document.body.classList.add("exportingToVideo");
this.i.Sa().style.display="";this.i.yb()});c.h("runtime","export-to-video-progress",b=>Ha(this,b));c.h("runtime","exported-to-video",b=>{window.dc({type:"exported-video",arrayBuffer:b.arrayBuffer,contentType:b.contentType,time:b.time})});c.h("runtime","exported-to-image-sequence",b=>{window.dc({type:"exported-image-sequence",blobArr:b.blobArr,time:b.time,gif:b.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",b=>{const d=b.target;a.has(d.tagName.toLowerCase())||
sa(d)||b.preventDefault()});window.addEventListener("selectstart",P);window.addEventListener("gesturehold",P);window.addEventListener("touchstart",P,{passive:!1});window.addEventListener("pointerdown",P,{passive:!1});this.Ha=0;window.addEventListener("mousedown",b=>{1===b.button&&b.preventDefault()});window.addEventListener("mousewheel",va,{passive:!1});window.addEventListener("wheel",va,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.s&&this.ib){var b=this.u();var d=this.o();if(this.i.Ta()){if(this.hb){if(this.Ea===
b&&d<this.$){this.ca=this.$-d;Y(this,this.$,this.ca);b=void 0;break a}0<this.ca&&(this.ca=0,Y(this,d,this.ca))}this.Ea=b;this.$=d}m(this,"window-resize",{innerWidth:b,innerHeight:d,devicePixelRatio:window.devicePixelRatio,isFullscreen:L.S(),cssDisplayMode:this.i.sa()});this.i.T()&&(-1!==this.M&&clearTimeout(this.M),Ja(this,b,d,0))}b=void 0}return b});window.addEventListener("fullscreenchange",()=>J(this));window.addEventListener("webkitfullscreenchange",()=>J(this));window.addEventListener("mozfullscreenchange",
()=>J(this));window.addEventListener("fullscreenerror",b=>V(this,b));window.addEventListener("webkitfullscreenerror",b=>V(this,b));window.addEventListener("mozfullscreenerror",b=>V(this,b));if(c.T()){let b=Infinity;window.visualViewport.addEventListener("resize",()=>{const d=window.visualViewport.height;d>b&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0);b=d});document.documentElement.setAttribute("ioswebview","")}this.Ga=new Set;this.ac=new WeakSet;this.Yb=!1}Oa(){window.addEventListener("focus",
()=>{m(this,"window-focus",null,O)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(b){a=!1}m(this,"window-blur",{parentHasFocus:a},O);this.Ha=0});window.addEventListener("focusin",a=>{a=a.target;(ta.has(a.tagName.toLowerCase())||sa(a))&&m(this,"keyboard-blur",null,O)});window.addEventListener("keydown",a=>Ia(this,"keydown",a));window.addEventListener("keyup",a=>Ia(this,"keyup",a));window.addEventListener("mousedown",a=>W(this,"mousedown",a,N));
window.addEventListener("mousemove",a=>W(this,"mousemove",a,N));window.addEventListener("mouseup",a=>W(this,"mouseup",a,N));window.addEventListener("dblclick",a=>W(this,"dblclick",a,M));window.addEventListener("wheel",a=>{this.s||m(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.B,pageX:a.pageX,pageY:a.pageY+this.B,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},M)});window.addEventListener("pointerdown",a=>{window!==window.top&&window.focus();La(a.target)&&
document.activeElement&&!La(document.activeElement)&&document.activeElement.blur();X(this,"pointerdown",a)});this.i.m&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{X(this,"pointermove",a)}):window.addEventListener("pointermove",a=>X(this,"pointermove",a));window.addEventListener("pointerup",a=>X(this,"pointerup",a));window.addEventListener("pointercancel",a=>X(this,"pointercancel",a));const c=()=>this.va();window.addEventListener("pointerup",
c,!0);window.addEventListener("touchend",c,!0);window.addEventListener("click",c,!0);window.addEventListener("keydown",c,!0);window.addEventListener("gamepadconnected",c,!0);this.i.tb()&&!this.i.Ta()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{Y(this,this.o(),navigator.virtualKeyboard.boundingRect.height)}));this.i.T()&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0)}u(){return this.i.u()}o(){return this.i.o()}va(){var c=
[...this.Ga];this.Ga.clear();if(!this.Yb)for(const a of c)(c=a.play())&&c.catch(()=>{this.ac.has(a)||this.Ga.add(a)})}});"use strict";async function ka(c){if(c.Xb)throw Error("already initialised");c.Xb=!0;var a=c.A.ua(("playable-ad"===c.A.g?c.A.L:"")+"dispatchworker.js");c.ya=await c.A.ra(a,c.X,{name:"DispatchWorker"});a=new MessageChannel;c.Ba=a.port1;c.ya.postMessage({type:"_init","in-port":a.port2},[a.port2]);c.Ia=await na(c)}function la(c){return[c.Ba,c.Ia]}
async function na(c){const a=c.nb.length;var b=c.A.ua(("playable-ad"===c.A.g?c.A.L:"")+"jobworker.js");b=await c.A.ra(b,c.X,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;c.ya.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);b.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);c.nb.push(b);return e.port1}
self.wb=class{constructor(c){this.A=c;this.X=c.l;this.X="preview"===c.g?this.X+"workers/":this.X+c.L;this.$b=Math.min(navigator.hardwareConcurrency||2,16);this.ya=null;this.nb=[];this.Ia=this.Ba=null}};"use strict";window.C3_Is_Supported&&(window.c3_runtimeInterface=new self.U({nc:!0,oc:"workermain.js",P:["scripts/c3runtime.js"],oa:[],Na:"",kc:"scripts/",pa:[],qb:"html5"}));"use strict";
self.U.fa(class extends self.R{constructor(c){super(c,"mouse");u(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.i.Sa().requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{m(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{m(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
"use strict";async function Ma(c,a){a=a.type;let b=!0;0===a?b=await Na():1===a&&(b=await Oa());m(c,"permission-result",{type:a,result:b})}async function Na(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(c){return console.warn("[Touch] Failed to request orientation permission: ",c),!1}}
async function Oa(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(c){return console.warn("[Touch] Failed to request motion permission: ",c),!1}}self.U.fa(class extends self.R{constructor(c){super(c,"touch");t(this,"request-permission",a=>Ma(this,a))}});"use strict";let Pa=!1;
async function Ra(c){var a=Sa(c.index);if(a&&(a=a.vibrationActuator)&&a.playEffect)try{await a.playEffect("dual-rumble",{duration:c.duration,startDelay:0,weakMagnitude:c.weakMag,strongMagnitude:c.strongMag})}catch(b){console.warn("[Gamepad] Failed to vibrate gamepad: ",b)}}function Z(){try{return Array.from(navigator.getGamepads()).filter(c=>c&&c.connected)}catch(c){return Pa||(console.warn("[Construct] Failed to access gamepads: ",c),Pa=!0),[]}}
function Ta(c){-1===c.N&&(c.N=setInterval(()=>Ua(c),4))}function Ua(c){var a=Z();a.length&&(a=a.map(b=>({index:b.index,id:b.id,buttons:b.buttons.map(d=>({pressed:d.pressed,value:d.value})),axes:b.axes})),m(c,"input-update",a))}function Sa(c){for(const a of Z())if(a.index===c)return a;return null}
self.U.fa(class extends self.R{constructor(c){super(c,"gamepad");this.Da=!1;this.N=-1;t(this,"ready",()=>{this.Da=!0;for(const a of Z())m(this,"gamepad-connected",{index:a.index,id:a.id});Ta(this)});t(this,"vibrate",a=>Ra(a));t(this,"reset-vibrate",a=>{(a=Sa(a.index))&&(a=a.vibrationActuator)&&a.reset&&a.reset()});t(this,"suspend",()=>{-1!==this.N&&(clearInterval(this.N),this.N=-1)});t(this,"resume",()=>{Ta(this)});window.addEventListener("gamepadconnected",a=>{this.Da&&(a=a.gamepad,m(this,"gamepad-connected",
{index:a.index,id:a.id}))});window.addEventListener("gamepaddisconnected",a=>{this.Da&&m(this,"gamepad-disconnected",{index:a.gamepad.index})});window.addEventListener("unload",()=>{for(const a of Z()){const b=a.vibrationActuator;b&&b.reset&&b.reset()}})}});
